### ISSUE TITLE
People page incorrectly pulls TestOrder, not TestResults

### ISSUE THREAD

**Issue by sharmaneil** [CDCgov/prime-data-input-client#275]
# Bug 1: Invalid TestOrders on history page

# # Steps to reproduce:
1. add a patient to the queue
2. update their AoE form but don't submit
3. go to the people tab and select the patient
4. The test history would have a new entry even tho the test hasn't been submitted

![bug](https://user-images.githubusercontent.com/35268641/101695782-f4cbd000-3a29-11eb-9eb2-406d947d08f1.gif)

# Bug 2 -  there is a stray 0 if there are no test results in the history
<img width="161" alt="Screen Shot 2020-12-09 at 5 39 47 PM" src="https://user-images.githubusercontent.com/35268641/101710130-c22fd080-3a45-11eb-8a9e-ca1c0a5372f6.png">

**Comment by timothybest-usds** [comment]
Bug 1 requires some backend work:

in the api {patient { testResults}} pulls fromTestOrder when it should pull from TestEvent

**Comment by benwarfield-usds** [comment]
Hypothetical question for the design team for future state: should the patient view show only tests that took place in this organization, or should it include send-out tests, when we include send-out tests?

**Comment by TomNUSDS** [comment]
> Bug 1 requires some backend work:
> 
> in the api {patient { testResults}} pulls fromTestOrder when it should pull from TestEvent

@dmethvin-gov and I were just looking at this bug and the work around fixing it.

**Comment by dmethvin-gov** [comment]
Mentioned in Slack ... the problem is in the graphql schema but that impacts the backend as well. Not sure what specifically would be required to fix it. 
[ https://github.com/CDCgov/prime-data-input-client/blob/3b84fbb8ef13f34c27645429da08c0899c1d42f9/backend/src/main/resources/schema.graphqls#L33](Schema)

We have an `ApiTestOrder` in the backend but not an `ApiTestResult`. These appear to be super boilerplatey, are they generated from somewhere? If so I might be able to create one if the steps are written somewhere.

**Comment by katiealoisi** [comment]
By patient view, do you mean the Profiles within SimpleReport or the future state patient app? If you're talking about SimpleReport, based on initial feedback we've heard it would be helpful to include send-out tests in the Test History. @hmyers-cms

**Comment by benwarfield-usds** [comment]
I mean the thing in the picture up top. :-)
