### ISSUE TITLE
Test Results appear mutable on the frontend

### ISSUE THREAD

**Issue by sharmaneil** [CDCgov/prime-data-input-client#280]
## About
This might just be my misunderstanding, but I thought test results are supposed to be immutable and capture all information at the time it was saved. Any edits should not update the test result. 

## Bug
If you change the patient's name, the test result changes too. This might apply to other variables.

![mutable or not](https://user-images.githubusercontent.com/35268641/101713871-5e110a80-3a4d-11eb-952d-e4d8db823c0e.gif)

## Notes

- I did not verify if the db test result is also being mutated.
- If this behavior is intentional, feel free to close the issue

**Comment by benwarfield-usds** [comment]
There is not a persistence-layer issue here, but there is a choice that may or may not have been made intentionally: we save a link to the live patient information (so we can find all the tests in somebody's history), and we also save a snapshot of the patient information (so that we know what we were looking at when we administered the test). On this screen we're using the live information, rather than the snapshot, and I don't know if that's a feature or a bug. 😄 

(In the export for PHD, we use the snapshot.)

**Comment by sharmaneil** [comment]
Thanks @benwarfield-usds for verifying its not a persistence issue 😌 . Definitely pushes this down the list of priorities. I do not recall if this was an intentional design decision.

@hmyers-cms @katiealoisi, would either of you know what the desired behavior is?

**Comment by dmethvin-gov** [comment]
Yeah this is a tough one from a UX perspective. The historical info is in the TestOrder but not returned to the frontend right now; we only get the live patient info. If we got both things I suppose we could compare them and somehow flag that yes, the info in the historical test result doesn't match.

**Comment by timothybest-usds** [comment]
It is my understanding that this is a bug and we should be displaying the data record at time of test until we build the a way to edit records. see https://github.com/CDCgov/prime-central/issues/173
