### ISSUE TITLE
Define GraphQL queries for MVP, build out endpoints

### ISSUE THREAD

**Issue by sharmaneil** [CDCgov/prime-data-input-client#48]
## About

This is the queries/mutations/subscriptions the frontend probably will need for an MVP

### Patients
- QUERY: get all patients 
- MUTATION: add single patient
- MUTATION: add multiple

#### Fields the front end currently uses:
```
patientId
firstName
middleName
lastName
birthDate
address (this should probably be broken down into street 1, street 2, city, state, zip, etc)
phone
```

#### Fields the csv upload provides
```
        patientID,
        patientLastName,
        patientFirstName,
        patientMiddleName,
        patientSuffix,
        patientRace,
        patientDOB,
        patientGender,
        patientEthnicity,
        patientStreet,
        patientStreet2,
        patientCity,
        patientCounty,
        patientState,
        patientZipCode,
        patientPhoneNumber,
        patientEmail,
        patientAge,
        employedInHealthcare,
        typeOfHealthcareProfessional,
        residentCongregateSetting,
        patientResidencyType,
```

Probably would also want metadata fields, like `dateCreated` or `lastUpdated` to help with sync too.

###  Organization
- QUERY: get org data
```
Testing Facility Name
CLIA Number
Ordering Provider Name
Ordering Provider NPI
Ordering Provider Address
Ordering Provider Zip Code
Ordering Provider Phone Number
```
- MUTATION: update org information

TBD: determine if we need dynamic AoE questions, and an adjustableAoE model

###  TestResults
- QUERY: get all test results
- MUTATION: add a test result for a single patient

```
deviceId
result
dateTested
aoeResponse
<patient information at the time of test>
```

###  Queue:
- QUERY: get all patients in the queue
- MUTATION: add patient to the Queue
- MUTATION: update time of test questions
- MUTATION: update device + test result (TBD: confirm with product)
- MUTATION: remove patient from the queue

```
each item in the queue has:
- patientId
- dateAdded
- aoeResponse
```

###  CSV Export History:
- MUTATION: save timestamp and the csv of last upload to Prime Hub

###  User:
- QUERY: get current user

###  Devices:
- QUERY; get all devices
- MUTATION: set all devices (not update)

#### Frontend only really needs:
```
displayName 
isDefault
```

Sounds like we might also want, for the export:
```
deviceManufacturer
deviceModel
```

**Comment by benwarfield-usds** [comment]
A couple points on these:

* I think there are two things overlapping here somewhat dangerously: Organization (an entity that we probably need some users to be able to list, but most users belong to one and don't know about the others), and Configuration (the choices made by the organization). We should probably have graphql endpoints for querying and updating organizations, because we should eat our own dogfood, but mostly people should be doing `get my organization` and `get the configuration for my organization`. (So actually they would probably do `get the current user and the associated organization` now that I stop to think about it.)
* Devices are the perfect example: we need a global list of valid devices, but non-admin users don't need that list, they need the list that is configured for their site.
* Queue entries have patients and a bunch of other data which may be different by site: the ask-on-entry questions need to be in there, at least, and arguably we should be able to select which machine a test is going to run on and have that be saved even if we haven't gotten the result back yet
* Auth should just be auth and should not be part of graphql

**Comment by benwarfield-usds** [comment]
More broadly: I don't know how graphql is typically structured, but in the sample it looks like everything is either a "method" of `Query` or `Mutation`. Is that a requirement, a convention, or just a convenience for introducing people to things? I think we might want to have some organization beyond the flat single level of named queries, but maybe that's the old REST fan in me... 😜

**Comment by pete-usds** [comment]
> More broadly: I don't know how graphql is typically structured, but in the sample it looks like everything is either a "method" of `Query` or `Mutation`.

I think we have to define the types and resolves for queries (roughly, reads) and mutations (roughly, create-update-delete) separately. They're entirely different things that are both necessary.

You can see examples here: https://github.com/CDCgov/prime-data-input-client/blob/main/backend-graphql-dev/src/server.js

**Comment by benwarfield-usds** [comment]
Answering my own question: that is either a sufficiently strong convention that it might as well be a requirement or a requirement, so if we want to organize the schema logically we'll have to pretend it's 1985 and we just discovered long identifier names.
